### PR TITLE
Fix: exclude default timestamp column with upsert

### LINKED ISSUE #12: bug: upsert overwrites createdAtTime
eg: when processPlatformTracks.ts upserts artist/artist profiles, it changes the createdTime for those artists

### PR DESCRIPTION
**Pull request by puffo**
Resolves #12

### CODE REVIEW

File: src/db/db.ts [hunk 1]
```diff
@@ -2,6 +2,8 @@ import { Knex } from 'knex';
 
 import { Cursor } from '../types/trigger'
 
+export const defaultTimestampColumn = 'createdAtTime';
```
Comment (puffo) [inline src/db/db.ts:5]: Not sure if we want to rather stick with an enum to allow for future extension? i.e. something like
```javascript
export enum DefaultTimestampColumn {
  createdAtTime = 'createdAtTime'
}
```
Thoughts?

Comment (musnit) [reply src/db/db.ts:5]: not sure exactly what you mean / what you imagine future possible extension would be?

Comment (puffo) [reply src/db/db.ts:5]: I was thinking about `updatedAtTime`, but in the case of an upsert we'd probably want to affect that column. 

If you're good with just a simple `const`, then let's roll on with [YAGNI](https://en.wikipedia.org/wiki/You_aren't_gonna_need_it)!

**Review by musnit — APPROVED** [review]
